version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: "{{ wp_host }}" # db
      WORDPRESS_DB_USER: "{{ wp_user }}" # admin 
      WORDPRESS_DB_PASSWORD: "{{ wp_pwd }}" # 4242
      WORDPRESS_DB_NAME: "{{ wp_name }}" # wordpress
    volumes:
      - wordpress_data:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "9090:80"
    depends_on:
      - db
    environment:
      PMA_HOST: "{{ pma_host }}" # db
      MYSQL_ROOT_PASSWORD: "{{ mysql_pwd }}" # 4242

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "{{ mysql_pwd }}" # root
      MYSQL_DATABASE: "{{ mysql_db }}" # wordpress
      MYSQL_USER: "{{ mysql_user }}" # admin
      MYSQL_PASSWORD: "{{ mysql_pwd }}" # 4242
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
