- name: Installing and setting-up WordPress
  hosts: myhosts
  tasks:
    - name: Get docker-compose from host
      copy:
        src: ../docker-compose.yml
        dest: .

    - name: Get from containers repo from host
      copy:
        src: ../containers
        dest: .

    - name: Get secrets
      include_vars:
        file: secrets.yml
        name: secrets

    - name: docker-compose up -d with secrets
      command: docker-compose up -d
      environment:
        WP_USER: "{{ secrets.wp_user }}"
        WP_PWD: "{{ secrets.wp_pwd }}"
        WP_DB_HOST: "{{ secrets.wp_db_host }}"
        WP_DB_USER: "{{ secrets.wp_db_user }}"
        WP_DB_PWD: "{{ secrets.wp_db_pwd }}"
        WP_DB_NAME: "{{ secrets.wp_db_name }}"
        PMA_HOST: "{{ secrets.pma_host }}"
        MYSQL_ROOT_PWD: "{{ secrets.mysql_root_pwd }}"
        MYSQL_PWD: "{{ secrets.mysql_pwd }}"
        MYSQL_DB: "{{ secrets.mysql_db }}"
        MYSQL_USER: "{{ secrets.mysql_user }}"
