- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - wp
    - nginx

- name: Get docker-compose from host
  template:
    src: docker-compose.yml.j2
    dest: docker-compose.yml

- name: Get wp-config.php
  template:
    src: wp-config.php.j2
    dest: wp/wp-config.php

- name: Get WordPress install script
  template:
    src: wp_install.sh.j2
    dest: wp/wp_install.sh

- name: Get WordPress Dockerfile
  copy:
    src: wp_Dockerfile
    dest: wp/Dockerfile

- name: Get nginx Dockerfile
  copy:
    src: nginx_Dockerfile
    dest: nginx/Dockerfile

- name: Get www.conf
  copy:
    src: www.conf
    dest: wp/www.conf

- name: Get nginx.conf
  copy:
    src: nginx.conf
    dest: nginx/nginx.conf

- name: Get rature.fr.conf
  template:
    src: apitoise.rature.fr.conf.j2
    dest: nginx/apitoise.rature.fr.conf

- name: Get certificate.crt
  copy:
    src: certificate.crt
    dest: nginx/certificate.crt

- name: Get private.key
  copy:
    src: private.key
    dest: nginx/private.key

- name: docker-compose up -d with secrets
  command: docker-compose up -d
